---
title: "Pandemic Pass? Treaty Derogations and Human Rights Practices During COVID-19"
short-title: "Pandemic Pass?"
subtitle: "(Research note)"
author:
- name: Suparna Chaudhry
  affiliation: Lewis and Clark College
  orcid: 0000-0003-3506-7590
  url: https://www.suparnachaudhry.com/
  email: schaudhry@lclark.edu
- name: Audrey L. Comstock
  affiliation: Arizona State University
  orcid: 0000-0003-1772-5350
  url: https://audreylcomstock.weebly.com/
  email: audrey.comstock@asu.edu
- name: Andrew Heiss
  affiliations: 
    - id: gsu
      name: Georgia State University
      department: Andrew Young School of Policy Studies, Department of Public Management and Policy
      address: "55 Park Place NE, #464"
      city: Atlanta
      region: GA
      country: USA
      postal-code: 30303
  orcid: 0000-0002-3948-3914
  url: https://www.andrewheiss.com
  email: aheiss@gsu.edu
  attributes:
    corresponding: true
correspondence-prefix: "Correspondence concerning this article should be addressed to"
abstract: |
  This research note asks whether...
thanks: |
  We would like to thank participants .
date: July 25, 2024
code-repo: "Access the code, data, and analysis at <https://github.com/andrewheiss/mountainous-mackerel>"
keywords:
  - human rights
  - treaty derogations
  - COVID-19
  - emergency policies
bibliography: bib/CARIPARMA.bib
csl: bib/chicago-author-date.csl
link-citations: true
---

```{r setup, include=FALSE}
if (is.null(knitr::pandoc_to())) {
  fmt_out <- "interactive"
} else {
  fmt_out <- knitr::pandoc_to()
}

knitr::opts_chunk$set(echo = FALSE, include = FALSE, 
                      warning = FALSE, message = FALSE)

knitr::opts_chunk$set(fig.align = "center", fig.retina = 3,
                      fig.width = 6, fig.height = (6 * 0.618),
                      out.width = "80%", collapse = TRUE)

options(digits = 3, width = 120,
        dplyr.summarise.inform = FALSE,
        knitr.kable.NA = "")
```

```{r libraries-data}
library(tidyverse)
library(scales)
library(sf)
library(lubridate)
# library(tidybayes)
# library(marginaleffects)
library(patchwork)
library(colorspace)
library(tinytable)
library(kableExtra)
# library(targets)

# tar_config_set(store = here::here('_targets'),
#                script = here::here('_targets.R'))
# 
# # Generated via random.org
# set.seed(8511)
# 
# # Load targets 
# weekly_panel <- tar_read(weekly_panel) %>% 
#   mutate(year_week_day = ymd(year_week_day))
# 
# quarterly_panel <- tar_read(quarterly_panel) %>% 
#   mutate(year_quarter_day = ymd(year_quarter_day))
# 
# tar_load(c(policies_plot_data, human_rights_plot_data))
# tar_load(c(policies_table_data, hr_table_data))
# tar_load(c(derogation_map_data, derogation_count))
# 
# # Plotting and modelsummary functions
# invisible(list2env(tar_read(graphic_functions), .GlobalEnv))
# invisible(list2env(tar_read(modelsummary_functions), .GlobalEnv))
```

 
::: {.content-visible when-format="html"}
# Introduction {.hide}
:::

Did states misuse international emergency provisions during the COVID-19 crisis to justify human rights abuse? As said by [@ministerodellavoroedellepolitichesocialiDECRETO23Luglio2019] 

# Conclusion

Blah blah blah.   

# References

::: {#refs}
:::
